
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @param firstNum
     * @param secondNum
     * @return
     *     returns int
     */
    @WebMethod(action = "http://tempuri.org/simpleMethod")
    @WebResult(name = "simpleMethodResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "simpleMethod", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SimpleMethod")
    @ResponseWrapper(localName = "simpleMethodResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SimpleMethodResponse")
    public int simpleMethod(
        @WebParam(name = "firstNum", targetNamespace = "http://tempuri.org/")
        int firstNum,
        @WebParam(name = "secondNum", targetNamespace = "http://tempuri.org/")
        int secondNum);

}
